### ISSUE TITLE
[talk suggestion] How fast is it really? Benchmarking in practice

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#1]
I gave this talk at Elixirlive and it was generally well received. It's general benchmarking advice intertwined with samples and benchee sample code.

My first talk at elixir.berlin months ago was a little impromptu benchee talk without much preparation, it has grown considerably since then so I'd like to share general benchmarking knowledge and an update on benchee :)

Abstract

“What’s the fastest way of doing this?” - you might ask yourself during development. Sure, you can guess what’s fastest or how long something will take, but do you know? How long does it take to sort a list of 1 Million elements? Are tail-recursive functions always the fastest?

Benchmarking is here to answer these questions. However, there are many pitfalls around setting up a good benchmark and interpreting the results. This talk will guide you through, introduce best practices and show you some surprising benchmarking results along the way.

moved from Trello - suggestion from @PragTob

**Comment by duksis** [comment]
@PragTob so in January at your office?

**Comment by PragTob** [comment]
I can do whenever is most convenient for the meetup, talk is "ready" I just need to trim it down to your preferred length (at elixirlive we had 50 minutes and that's exactly how long I needed) :)

**Comment by slashmili** [comment]
Next meetup is 12th Jan, I added this talk to that meetup agenda

**Comment by PragTob** [comment]
So what's the preferred talk length so I can cut accordingly?

Happy holidays!

**Comment by slashmili** [comment]
This the only talk for Jan, So we have plenty time :) I could be 30 min or more

**Comment by PragTob** [comment]
Well I'll trim it a bit then, original version was 50 minutes (that was their preferred time :D) :)
