### ISSUE TITLE
Location/Host for June

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#10]
We are looking for location/hosts for our June event 
In case your company would be willing to host us on 8th of June please raise your :raise_hand: here

**Comment by duksis** [comment]
extract from #8 
```
@slashmili Currently our hr and me are sick and I could not 100% answer the question for May. I think we do not handle it in this month. For that reason, to not blocking you I would like to postpone Elixir meetup in Qixxit for May.
Keep in touch.
```

@barsukov get well soon! when you are back on track please check with your HR for the 8th of June

**Comment by xhr15** [comment]
as always, if that doesn't work, @bitcrowd can step in as host

**Comment by barsukov** [comment]
@duksis Yeah, sure I will ask her for the dates when we can handle a meetup.
