### ISSUE TITLE
#37 Talks for July 

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#12]
@mindreframer you wanted to show some monorepo project tooling. Will you be able to share that with us on the 13th of July?

----
Talk suggestions / requests welcome

**Comment by mindreframer** [comment]
@duksis OK, I will give a short talk about monorepos and tooling around it. )))

**Comment by leifg** [comment]
I can give a talk on releases with [distillery](https://github.com/bitwalker/distillery)

**Comment by surik** [comment]
I and @mgumz want to talk about OpenTracing and [otter](https://github.com/Bluehouse-Technology/otter).

**Comment by duksis** [comment]
@surik @mgumz is the August meetup ok for you guys?

**Comment by surik** [comment]
@duksis I'm not sure about August. Can we do it today? ;)

**Comment by mgumz** [comment]
@duksis how much time is there per talk? sadly i am @vaction in 2017-08.

**Comment by duksis** [comment]
@mgumz would be optimal 30-40 min 
@surik should be possible today as well
