### ISSUE TITLE
#38 Talks for August

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#13]
Agenda: 

"Expressive power in Elixir" by @Dzol
"Migrating to Phoenix 1.3" by @lbighetti 
"Phoenix 'Hello World' without phoenix.new" by @muaazsaleem

**Comment by lbighetti** [comment]
I would like to speak on "Migrating to Phoenix 1.3"

**Comment by muaazsaleem** [comment]
Hi @duksis, I would like to do a talk on "Phoenix Hello World without phoenix.new".

**Comment by duksis** [comment]
added you to the list of speaker for August

**Comment by slashmili** [comment]
Thank you guys!
