### ISSUE TITLE
#40 Talks for October

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#18]
https://www.meetup.com/Elixir-Berlin/events/239187369/

Please submit talk suggestions and requests here in comments

current agenda:

* NIFs and C Nodes - by @Overbryd 
* Building an api from scratch with Phoenix - by @lbighetti 
* lightning talk "code insurance" - by @devonestes

**Comment by devonestes** [comment]
I think I'll bring a lightning talk - just a quick 5 minutes on code insurance 😉

**Comment by duksis** [comment]
"code insurance" sounds like a very German thing :)

**Comment by lbighetti** [comment]
I would like to speak on `Building an api from scratch with Phoenix`
