### ISSUE TITLE
#40 Location for October

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#19]
https://www.meetup.com/Elixir-Berlin/events/239187369/

**Comment by ggcampinho** [comment]
I'm checking if SoundCloud can host the event

**Comment by ggcampinho** [comment]
I have the classroom here reserved, it fits up to 50 people, so I think we have enough space

**Comment by duksis** [comment]
nice - thank you @ggcampinho 
the address is still "Rheinsberger Str. 76/77, 10115 Berlin"?

**Comment by ggcampinho** [comment]
Correct!

**Comment by duksis** [comment]
I updated the meetup page and added you as the host representative on meetup.com

Thanks
