### ISSUE TITLE
#41 Location for November

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#20]
https://www.meetup.com/Elixir-Berlin/events/242094932/

**Comment by slashmili** [comment]
We can host the event in @highmobility

**Comment by duksis** [comment]
@slashmili what is the new location of @highmobility ?

**Comment by kevinvaldek** [comment]
Hey @duksis it's at:

High-Mobility GmbH
Kastanienallee 29-30
10435 Berlin
