### ISSUE TITLE
#42 December (Talks/Location)

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#22]
https://www.meetup.com/Elixir-Berlin/events/244139449/

* [x] Location (@bitcrowd)
* [x] Talks
  * "Elixir Deployment" by @Overbryd 
  * ~~"Preparing to scale with phoenix" by @f34nk~~
  * "Property Testing" by @lbighetti

**Comment by duksis** [comment]
@Overbryd "Elixir deployment" or "Stream processing using GenStage" ? :)

**Comment by duksis** [comment]
@f34nk "Scaling with phoenix" ?

**Comment by Overbryd** [comment]
I‘ll do one about „Elixir Deployment“ for December.

Hugo Duksis <notifications@github.com> schrieb am Do. 9. Nov. 2017 um 14:25:

**Comment by psychocandy** [comment]
We (https://www.kloeckner-i.com/) would be happy to host the meetup at our office if you're still looking for a location.

**Comment by f34nk1** [comment]
Hello, sorry for cross posting:
Yes I will be able to do the december talk. However I focused the topic a little bit.
"Preparing to scale with phoenix" should be much clearer.
Best,
Frank

**Comment by f34nk** [comment]
Hello, sorry for cross posting:
Yes I will be able to do the december talk. However I focused the topic a little bit.
"Preparing to scale with phoenix" should be much clearer.
Best,
Frank

**Comment by lbighetti** [comment]
I would like to do a talk on `Property Testing`

**Comment by f34nk** [comment]
Unfortunately I have to postpone my talk to next year. Something unexpected came up and I can not attend to the meeting next week.
I am happy to give the talk another time :)

**Comment by duksis** [comment]
@f34nk when would it be the best for you - January or February?

**Comment by f34nk** [comment]
Hi @duksis. January is fine with me.
