### ISSUE TITLE
#43 January (Talks/Location)

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#23]
https://www.meetup.com/Elixir-Berlin/events/244139452

* [x] Location (https://www.kloeckner-i.com/) 
* [x] Talks
  * "date-based API versioning using Elixir & Phoenix" by @nburkley
  * "Preparing to scale with phoenix" by @f34nk
  * "Interop in Elixir: NIFs, Ports & Co" by @ndreynolds

**Comment by nburkley** [comment]
I'm putting together a talk on [stripe-like](https://stripe.com/blog/api-versioning) rolling, date-based API versioning using Elixir & Phoenix. I can give this in January if there's interest?

**Comment by duksis** [comment]
I would like to hear that and I'm sure many others as well - I'll add "date-based API versioning using Elixir & Phoenix" to the agenda

**Comment by duksis** [comment]
Moved talk from @f34nk from December to January

**Comment by ndreynolds** [comment]
If there's interest, I'd love to give a short talk on "Interop in Elixir: NIFs, Ports & Co."  Would give an overview of the different strategies for interfacing with native code and some examples in C & Rust.

**Comment by slashmili** [comment]
@ndreynolds do you think you can give the talk next week?

**Comment by ndreynolds** [comment]
@slashmili yeah, I can have it ready for the meetup next week.

**Comment by slashmili** [comment]
Great! see you next week 🎉
