### ISSUE TITLE
#44 February (Talks/Location)

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#24]
https://www.meetup.com/Elixir-Berlin/events/245186148/

* [x] Location (@qixxit)
* [x] Talks
  * __Blockchain Wallet with Elixir__ by @boc0 
  * __GraphQL__ by @duksis 
  * __Running test in cluster of nodes__ by @lorenzosinisi

**Comment by duksis** [comment]
Haven't done any talks for a while and have been working with GraphQL lately, thus thought maybe I can share my experience with [Absinthe](https://en.wikipedia.org/wiki/Absinthe) ;)

**Comment by duksis** [comment]
@paulodiniz what topic would you like to talk about?  :)

**Comment by boc0** [comment]
In case a spot is still free, I’d like to talk about an Elixir implementation of blockchain :)

**Comment by lorenzosinisi** [comment]
I could showcase my experience learning how to test code that should run in a cluster of nodes as I blogged here https://medium.com/@lorenzo_sinisi/how-to-test-elixir-cluster-of-nodes-using-slaves-69e59a77ec3f. What do you think?

**Comment by slashmili** [comment]
@lorenzosinisi That would be awesome! Do you think if it will be ready for 8th of Feb meetup?

**Comment by lorenzosinisi** [comment]
Yes sure!

**Comment by slashmili** [comment]
@lorenzosinisi Great

see you on Tuesday

**Comment by duksis** [comment]
you mean Thursday right? @slashmili

**Comment by slashmili** [comment]
@duksis Yes :/ my mistake
