### ISSUE TITLE
#45 March (Talks/Location)

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#25]
https://www.meetup.com/Elixir-Berlin/events/ngdpnmyxfblb/

* [x] Location (@solarisbank)
* [ ] Talks
  * "Your Monolith and Elixir becoming friends step by step" by @PragTob 
  * "Scraping government data with Elixir" by @paulodiniz 
  * ..

**Comment by lbighetti** [comment]
@paulodiniz ping
We wanna hear your talk 😛

**Comment by paulodiniz** [comment]
I can do a talk on extracting data and information about Brazilian political system.

Would anyone be interested?

**Comment by duksis** [comment]
If it's legal extraction than I'm interested :)

**Comment by PragTob** [comment]
Yo, on the website it looks like the time frame is roughly 30 minutes - is that right?

**Comment by duksis** [comment]
@PragTob yes that should be the suggested time - you need more or less?
