### ISSUE TITLE
#46 April (Talks/Location)

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#26]
https://www.meetup.com/Elixir-Berlin/events/ngdpnmyxgbqb/

* [x] Location @ bitcrowd
* [x] Talks
  * "It's a small world" by @devonestes
  * "Adele - Hello" by @Overbryd 
  * .... Free spot for Lightning talks

**Comment by Overbryd** [comment]
I would like to propose a talk about "Adele – Hello"

**Comment by duksis** [comment]
@Overbryd @devonestes the location is going to be Bitcrowd `Oranienstraße 6, 10997, Berlin`
