### ISSUE TITLE
#48 Jun (Talks/Location)

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#28]
https://www.meetup.com/Elixir-Berlin/events/ngdpnmyxjbsb

* [x] Location @ Wooga
* [x] Talks
  * Safety first with NIFs and Rustler @slashmili 
  * GraphQL your apps internal data API @duksis
  * .... Free spot for Lightning talks

**Comment by slashmili** [comment]
I can talk about **rustler**: _Safety first with NIFs and Rustler_

**Comment by duksis** [comment]
It still could be that my talk will be moved to lightning talks and a Elixir programming language documentary will be presented instead.
