### ISSUE TITLE
#49 July Talk and socialize

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#29]
https://www.meetup.com/Elixir-Berlin/events/ngdpnmyxkbqb/

* [x] Location (kloeckner.i)
* [x] Talks
  * "Integrating PostgreSQL's `file_fdw` with Ecto and Elixir to synch data sources" by @floriank 
  * "Elixir: A Mini-Documentary" by Josiah McGarvie
  * .. free spot for lightning talks

**Comment by amrabdelwahab** [comment]
@duksis if this spot is still empty I would move Modomoto here

**Comment by floriank** [comment]
@duksis 
I can offer a talk about an import pipeline we recently redesigned: 

```
Integrating PostgreSQL `file_fdw` with Ecto and Elixir to synch data sources
```

**Comment by duksis** [comment]
Added your talk @floriank - the email thing is weird went through all my deleted emails, spam box, archive and could not find it. Only thing I did not check is your draft folder ;-)

**Comment by floriank** [comment]
Let's better not check my drafts in order not to embarrass myself :1st_place_medal:
