### ISSUE TITLE
#55 January Talk and socialize

### ISSUE THREAD

**Issue by lbighetti** [elixir-berlin/planning#36]
* [x] Location (**[Entelios AG](https://entelios.de/)** - Kurfürstendamm 68, 3rd Floor)
* [x] Talks
   * Digging through the trash by @devonestes 
   * TwitterListManager running on Erlang by @metawilm

**Comment by duksis** [comment]
I'm playing around with https://www.erlang-solutions.com/products/wombatoam.html so I might be able to share my experience with that 
not sure though if it will be enough for a full sized talk - I'll confirm the length after this weekend

**Comment by devonestes** [comment]
I can give my talk "Digging through the trash" in January. I'm like 95% sure I'll be able to go unless something wacky happens with work.

**Comment by lbighetti** [comment]
Super!
Sounds like we have an agenda, it should be possible to do all 3 talks.
👍

**Comment by metawilm** [comment]
How much time would I have to present?

**Comment by leosilvadev** [comment]
Hey guys! I am still a newbie with Elixir but I would like to give a Lightning talk to show how I am using Codefresh as CI (and will use as CD also) for one Elixir project I am working in the free time.
Do you think it has time for that? Or would be better for the next one?

**Comment by duksis** [comment]
@metawilm 30 min would be optimal max 45 min
@leosilvadev in case there will be time after the talks we will be glad to give you 5 - 10 min to present your project - great to hear that you are working with Elixir in your free time!

**Comment by duksis** [comment]
Hello Ladies & Gentlemen,

With regret I have to postpone my talk to February do access issues to the proprietary software that I was going to talk about. 😞

**Comment by slashmili** [comment]
@leosilvadev do you think if you can give your Lightning talk today?

**Comment by leosilvadev** [comment]
Hey guys, unfortunately, I won't be able to even be present at the meetup today
I can do next month, and also will take some Sticker from the tool I will talk about (Codefresh)
