### ISSUE TITLE
#56 February Talk and socialize

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#37]
https://www.meetup.com/Elixir-Berlin/events/bcckcqyzdbsb/

* [x] Location @Adjust
* [x] Talks
   * "Managing translations in Elixir project with [Yata](http://www.yatapp.net)" by @luki3k5 
   * "Sending Millions of HTTP Requests Using GenStage" by @gaynetdinov 
   * free spot for lightning talks
* [x] Lightning talks
   * @ndreynolds

**Comment by marcelotto** [comment]
I'd like to give a talk about my projects implementing the W3C standards of the Semantic Web and Linked Data in Elixir, aiming to bring the Linked Data ecosystem to our beloved community.

**Comment by sumerman** [comment]
I remember promising you to host the meetup at Adjust. I'm not on vacation or whatnot this time, so it should work.

**Comment by leosilvadev** [comment]
I will be able to give a lightning talk that time, if there is still a spot, about using Codefresh as CI/CD for my elixir APIs

**Comment by marcelotto** [comment]
I'm really sorry but I have to cancel my talk. I was already sick for a week and now after just two days of working it hit me even harder again. I hope you find a replacement in time and it works out next time.

**Comment by gaynetdinov** [comment]
I can do a talk based on my recent blogpost http://adjust.github.io/2019-01/facebook-genstage/

**Comment by slashmili** [comment]
@marcelotto I hope you get better soon! Don't worry about it. Maybe next time 😉 

@gaynetdinov Interesting topic 👍 How long do you think you need for that?

**Comment by gaynetdinov** [comment]
@slashmili 30 min should be okayish I think.

**Comment by ndreynolds** [comment]
I'd also love to do a lightning talk this time if there's still room.  Would give a short demo of a project I've been working on.

**Comment by slashmili** [comment]
@ndreynolds That would be great 👍

**Comment by leosilvadev** [comment]
Guys I am really sorry but I won't be able to speak today again. My son and daughter are sick.
I hope that next time no shit happens again and I can do a lightning talk.
Sorry for the really late message

**Comment by slashmili** [comment]
@leosilvadev no problem. definitely next time
