### ISSUE TITLE
#57 March Talk and socialize

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#38]
https://www.meetup.com/Elixir-Berlin/events/bcckcqyzfbsb/

* [x] Location @sumup
* [x] Talks
   * "Introduction to Linked Data for Alchemists" by @marcelotto 
   * "Kubernetes as automation platform of multi-tenant deployments" by @mindreframer 
   * free spot for lightning talks

**Comment by duksis** [comment]
@surik will SumUp be able to host us on the 14th of March?

**Comment by surik** [comment]
Hi @duksis, SumUp will be happy to host you in March.

**Comment by duksis** [comment]
I'm working on a small, but full featured project (GraphQL backend with auth and payment) that should be live by the next meetup and I can share my experience with that - if there is interest.

**Comment by marcelotto** [comment]
I can give it another shot and give my "Introduction to Linked Data for Alchemists" talk. Hopefully, everything works out this time.

**Comment by mindreframer** [comment]
I could give a talk about Kubernetes as automation platform in the context of multi-tenant deployments and how to extend it with Elixir. I'll try to scope it by 20 minutes, although there is a ton of very interesting things that could be covered in that context.

**Comment by liveforeverx** [comment]
I will be on a meetup and can give a talk `Knowledge-based systems with Elixir`.

**Comment by slashmili** [comment]
@liveforeverx That would be really nice. How much time do you think you need for the talk?

**Comment by leosilvadev** [comment]
That week I will be able to join and give a lightning talk about how I am using Codefresh as CI/CD to my elixir projects if we have time

**Comment by duksis** [comment]
@leosilvadev depending on the length of @liveforeverx talk - there might be time for lightning talks or not

**Comment by leosilvadev** [comment]
@duksis no problem, I will join with my notebook, if we have time I talk about it, if not we try next time

**Comment by liveforeverx** [comment]
@duksis It will take ca. 30 minutes. But I propose to move my talk to April meetup, I will be there too and there is no speakers there at the moment in April.

**Comment by marcelotto** [comment]
I'm struggling a little with the time constraint of 30min for the talk. Since Linked Data is a huge topic, where even with strong simplifications and shortenings, I'll have to cover a lot of ground to make the Elixir implementation understandable. Would it be ok if I go beyond the 30 minutes or do I have to drop even more slides?

**Comment by duksis** [comment]
@marcelotto it's ok to go a bit over
