### ISSUE TITLE
#58 April Talk and socialize

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#39]
https://www.meetup.com/Elixir-Berlin/events/bcckcqyzgbpb/

* [x] @Adjust
* [x] Talks
   * "Knowledge-based systems with Elixir" by @liveforeverx
   * "Chunked to death or 1 Gb of garbage per minute." by @sumerman
   * free spot for lightning talks

**Comment by duksis** [comment]
adding @liveforeverx talk as suggested in https://github.com/elixir-berlin/planning/issues/38#issuecomment-471962771

**Comment by sumerman** [comment]
Adjust can provide the location.

**Comment by slashmili** [comment]
@sumerman that would be great! Thanks.

**Comment by sumerman** [comment]
I noticed there is no second talk. I have something for 15-20 minutes. "Chunked to death or 1 Gb of garbage per minute."
