### ISSUE TITLE
Location for March + Talk proposal @nextjournal 

### ISSUE THREAD

**Issue by zampino** [elixir-berlin/planning#4]
Hi Hugo and all Elixorians 

We'd like to host March (the 9th, right) meetup 
and give a talk about our Elixir stack at [nextjournal.com](https://nextjournal.com)
I'll give more details soon... 

we won't make it for February unfortunately ...

cheers Andrea (@zampino)

**Comment by duksis** [comment]
@zampino how sure are you that nextjournal.com can host us for the March meetup - 
can I update meetup page?

**Comment by zampino** [comment]
sure! 

we'll have a space limitation of `15` people officially,
the address is 

```
Nextjournal GmbH
schinkestr. 9, 2. HH
12047 Berlin, 
```

the talk I'm going to present could sound like:

_building a web-based multi-language live-coding editor with Phoenix and GenStage_

**Comment by duksis** [comment]
Updated meetup page and added you to @zampino as the event host for March :)

**Comment by behrtam** [comment]
Do you think I can get something from the talk even with very little elixir knowledge?

**Comment by duksis** [comment]
@behrtam yes :)

**Comment by jaigouk** [comment]
@zampino  could you share the slides for the talk?
