### ISSUE TITLE
#59 May Talk and socialize

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#40]
https://www.meetup.com/Elixir-Berlin/events/bcckcqyzhbmb/

* [x] Location (Qixxit)
* [ ] Talks
   * .. 
   * ..
   * free spot for lightning talks

**Comment by mkx** [comment]
We at Qixxit are interested in hosting the May talk. We just moved to a new office with a nice view on the sunset :)

**Comment by kpanic** [comment]
Also we (Taxfix) are interested in hosting one of the next meetup

**Comment by duksis** [comment]
@mkx What is the address of your new office, we will need someone from Qixxit to help us - would that person be you or Ina?

**Comment by mkx** [comment]
@duksis We are at Hallesches Ufer 60, 6th floor (former Postbank Tower). Let's continue with email, can you reach out to Ina?
