### ISSUE TITLE
#60 June Talk and socialize

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#41]
https://www.meetup.com/Elixir-Berlin/events/bcckcqyzjbrb/

* [x] Location: @taxfix
* [x] Talks
   * "" by @liveforeverx
   * "Ahoi! - hosting and administering complex software on Kubernetes" by @Overbryd
   * free spot for lightning talks

**Comment by kpanic** [comment]
That was quick. We (Taxfix) we would like to host this one :)

**Comment by danielvamosi** [comment]
@duksis As we discussed last Elixir meetup, [flyiin](flyiin.com) would be happy to host the one in July! cc @slashmili

**Comment by liveforeverx** [comment]
I would prepare one talk. Not sure yet, which one.. A story about parsing languages in Elixir or about my graph database adapter(where I'm working on minimal ecto-like DSL) open source project.

**Comment by Overbryd** [comment]
I would like to give a talk named “Ahoi!” where I will share my insights on hosting and administering complex software on Kubernetes.

Elixir plays a key role in automating this process, and I will show where Kubernetes is actually complementing the BeamVM.

Kind regards,


Lukas Rieder

**Comment by duksis** [comment]
@liveforeverx have you decided what you want to talk about?

**Comment by liveforeverx** [comment]
@duksis Yes, sorry for late answer: `Language integrated graph persistence`.
