### ISSUE TITLE
#68 February Talk and socialize

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#49]
https://www.meetup.com/Elixir-Berlin/events/gdsglrybcdbrb/

* [x] Location: @bitcrowd
* [x] Talks
   * "Abstract cache store for Elixir" by @duksis 
   * "> remote_observe" by @dominicletz
   * free spot for lightning talks

**Comment by dominicletz** [comment]
Hey, following the talk from Devon C. Estes last time on observability I created a small tool to automate the process of starting a local observer and doing all the needed port forwarding wire to any remote node.  https://github.com/dominicletz/remote_observe
Put some slides together I can show https://docs.google.com/presentation/d/1cts4pS2CxEa-CZDd7CwY6hfbHJj8hmiaT3fUNw4wk1w/edit#slide=id.g6ef5d5f58a_0_0
