### ISSUE TITLE
#69 March Talk and socialize

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#50]
https://www.meetup.com/Elixir-Berlin/events/gdsglrybcfbqb/

* [x] Location: @solarisBank
* [x] Talks
   *  "Design for scale and low maintenance" by Gheorghina
   *  "Green Organic Food with Elixir" by Ralph
* [ ] Lightning Talks:
   *  Type Systems on the BEAM (using Gleam) by @gordonguthrie
   * free spot for lightning talks

**Comment by flowerett** [comment]
Hello @duksis,
kloeckner.i would like to host the next meetup, hope the march slot is still free.
We also would like to reserve one slot for the talk.

**Comment by slashmili** [comment]
That would be great @flowerett! See you in March.

**Comment by slashmili** [comment]
Hi @flowerett, so I made a mistake and offered you Match slot while we already promised that to @solarisBank it was updated in [meetup](https://www.meetup.com/Elixir-Berlin/events/gdsglrybcfbqb/) but not here.

Would you be still interested to host us on May? I've create #52 for the May gathering.

Again sorry for the inconvenience

**Comment by flowerett** [comment]
Hello Milad,
it's a pity, but if we can't host the meetup in March then, of course, we would like to book the spot in May.

**Comment by alexanderspace100** [comment]
Hi there! Can I reserve the first talk slot for my colleague Gheorghina? Later, I'll be back with the title for it. Thanks

**Comment by gordonguthrie** [comment]
If you still have a slot for March I could talk about an approach for Type Systems on the BEAM (using Gleam)

https://medium.com/@gordonguthrie/types-on-the-beam-2af8b1cb9be9

(I am an 18 year Erlang veteran who also does Elixir and stuff)

**Comment by gordonguthrie** [comment]
Um, is that thumbs up a yes, come and talk?

**Comment by slashmili** [comment]
@gordonguthrie, Yes! We would to hear about Gleam!

**Comment by gordonguthrie** [comment]
Cool, see you then ;-)

**Comment by gordonguthrie** [comment]
Umm, come over all lightheaded with a sore throat, so not going anywhere tonight :-(

Sorry, maybe next month?

**Comment by gordonguthrie** [comment]
So I was also supposed to be interviewing with Solaris Bank tomorrow and they tell me the meetup is cancelled anyhoo...

**Comment by alexanderspace100** [comment]
This edition was canceled
