### ISSUE TITLE
#70 April Talk and socialize

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#51]
https://www.meetup.com/Elixir-Berlin/events/gdsglrybcgbmb/

* [x] Location: Online
* [x] Talks
   * "Design for scale and low maintenance" by @gheorghina
   * "Visual Concurrency Cookbook" @danielvamosi
   * free spot for lightning talks

**Comment by danielvamosi** [comment]
Hey @duksis , @flyiin would be happy to host the April meetup. I would like to also reserve a spot for a talk.

**Comment by slashmili** [comment]
Prefect @danielvamosi! Thanks for hosting us

**Comment by slashmili** [comment]
@danielvamosi do you still think you are able to host us? We totally understand if it's not possible. 

We are also evaluating if we should continue the event and do not put our community's health at risk.

**Comment by danielvamosi** [comment]
@slashmili @duksis unfortunately we are also introduced precautionary measures and wont be able to host on-site events. We were wondering, would you be interested in having April as a remote meetup? We would be very happy to help to organise such an event, both in terms of content and technical setup.

**Comment by duksis** [comment]
@danielvamosi thanks for the update - we are looking into options to make the meetup remote till the situation stabilises and your help is appreciated.

**Comment by alexanderspace100** [comment]
**Remote session requirements**

* [x] Communication channel
* [x] Talks. (we still have Daniel). I can ask Gheorghina if she wants to try it in this formula
* [x] Social media advertisement (besides our Twitter). Suggestion: [home conferences](https://github.com/homeferences/list) (https://remotemeetup.com/meetups)
*[x] How can we cover the lack of in-person interaction?
*[x] Can we engage people in a little game or something similar?

**Comment by alexanderspace100** [comment]
@gordonguthrie are you in for _Type Systems on the BEAM (using Gleam)_?

**Comment by danielvamosi** [comment]
@alexanderspace100 sorry for delayed response, busy days in flight industry 😞 

- For the communication channel, we could offer our help with @flyiin tech team to research best solution, maybe streaming, maybe web conferencing solution. Did you had already something in mind? 
- Regarding my talk, I'm open to any solution. I only realised now that some talks are shifting from the previous meet-up which sadly did not happen. To make space for those, I'm happy to do the same and postpone mine by a month. Or still make it if needed 💪

**Comment by slashmili** [comment]
Thanks @danielvamos!

We are good for two talks as long of you and @gheorghina are still able to join.

So we've decided to try discord as the communication channel and youtube as broadcasting channel. it's the setup that @overbryd has suggested.

We will give you instruction to check the setup before Thursday!

**Comment by slashmili** [comment]
@danielvamosi  & @gheorghina Could you please join using this discord https://discord.gg/WaKTXHD link

**Comment by gheorghina** [comment]
hello everyone, I managed to log into the discord app

**Comment by slashmili** [comment]
Thanks everyone!

It was a rad remote session 🎉
