### ISSUE TITLE
#71 May Talk and socialize

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#52]
https://www.meetup.com/Elixir-Berlin/events/gdsglrybchbsb/

* [x] Location: ONLINE
* [ ] Talks
   * .. 
   * ..
   * free spot for lightning talks

**Comment by flowerett** [comment]
Hello @slashmili, @duksis 
Seems the May is the nearest possible slot to host a meetup now, so I would like to book it for @kloeckner-i

**Comment by slashmili** [comment]
@flowerett due to the pandemic we are going to host the event live through youtube. Stay safe and looking to see you at @kloeckner-i after we are back to the normal life!

**Comment by alexanderspace100** [comment]
This edition was canceled due to lack of talks :(
