### ISSUE TITLE
Talk for April

### ISSUE THREAD

**Issue by devonestes** [elixir-berlin/planning#6]
Howdy!

So I'm not sure where we're having our April meetup, but I'd love to do a "dress rehearsal" of my talk for ElixirConf EU if folks are interested. Here's more info: http://www.elixirconf.eu/elixirconf2017/devon-estes

Hope to be there next week as well!

**Comment by slashmili** [comment]
Hey @devonestes !

That would be great. I updated the meetup page with your talk

The location is not settled yet but I guess we can work it out as usual :)

**Comment by devonestes** [comment]
Cool - guess I better polish up these slides, then! See you all in April!

**Comment by slashmili** [comment]
Was a great talk 👍
