### ISSUE TITLE
#80 February Talk and socialize

### ISSUE THREAD

**Issue by alexanderspace100** [elixir-berlin/planning#64]
https://www.meetup.com/Elixir-Berlin/events/gdsglryccdbpb/

* [x] Location: Remote
* [ ] Talks
   *  "web archiving with dust" by Sultan @imanhodjaev
   * "Writing a desktop application in Elixir" by @dominicletz
   * free spot for lightning talks

**Comment by alexanderspace100** [comment]
Hi @dominicletz. Nice to see you back with another talk. Sure, you are in. Please don't change your mind, as I will update the meetup page and that one is written in stone :)

**Comment by slashmili** [comment]
Hi @dominicletz could you please join our discord server https://discord.gg/WaKTXHD and ping me under user `milad`
