### ISSUE TITLE
#82 July Talk and socialize

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#68]
https://www.meetup.com/Elixir-Berlin/events/gdsglrycckblb/

* Time: 8th July 7pm CEST
* [x] Location: Remote
* [x] Talks
   * "Utilising OpenAPI to enforce standards between teams" by @floriank
   * free spot for lightning talks

**Comment by floriank** [comment]
I can offer a short talk about the benefits of utilizing OpenAPI to enforce standards between teams, creating mock APIs with [Mimicry](https://github.com/floriank/mimicry). Maybe it works by then as well.

Additionally, I can share some insights in working with [`DynamicSupervisor`](https://hexdocs.pm/elixir/1.12/DynamicSupervisor.html).

**Comment by floriank** [comment]
I have also asked internally, if we can use Contentfuls platform for hosting the meetup - will get back to y'all.

**Comment by floriank** [comment]
@duksis @slashmili  Enxhi from Contentful should have reached out to you for providing a platform to have the meeting :)

**Comment by duksis** [comment]
@floriank thank you for offering to use the Contentful platform for the meeting.
I think we would prefer going with our usual setup Youtube talk streaming + Discord for socialising
in case you insist in going with the Confluent one we can discuss that option.

I'd like to add you to the agenda and announce the event this week. 
as the talk name I can put `Utilising OpenAPI to enforce standards between teams`?

**Comment by floriank** [comment]
Yep, you can add that as a title!

**Comment by floriank** [comment]
> I think we would prefer going with our usual setup Youtube talk streaming + Discord for socialising

Btw. i think I misundersood this completely - I thought you were actively searching for a possible platform, hence me pushing the offer from Contentful.
