### ISSUE TITLE
#86 July Talk and socialize

### ISSUE THREAD

**Issue by dominicletz** [elixir-berlin/planning#73]
### Event URL

https://www.meetup.com/elixir-berlin/events/286485349/

### Time

14th July 7pm CEST

### Location

- [x] @highmobility
High-Mobility GmbH 
Skalitzer Str. 68, 10997
https://goo.gl/maps/Kbr7h5pkxoe4ndA86

### Talks

- [x] "Using Rust & Elixir to Conquer Regex" by @maciejgryka
- [ ] Registration Open - This might be you!

**Comment by slashmili** [comment]
we at @highmobility would like to host the next month event

**Comment by duksis** [comment]
@slashmili I accidentally removed the Location information - can you please re-add it?

**Comment by slashmili** [comment]
I'll also like to talk about "Telemetry and OpenTelemetry in Elixir"
