### ISSUE TITLE
#Nov 10th 2022 Talk and socialize

### ISSUE THREAD

**Issue by dominicletz** [elixir-berlin/planning#75]
### Event URL

[https://www.meetup.com/de-DE/elixir-berlin/events/289231408/](https://www.meetup.com/de-DE/elixir-berlin/events/289231408/)

### Time

10th September 19:00 CEST

### Location

- [x] kloeckner.i GmbH - Ackerstraße 14-15 · Berlin

### Talks

- [x] Make everything remotely-callable with Octopus by @antonmi
- [x] GraphQL "best" practices by @duksis

**Comment by agreif** [comment]
@dominicletz Hi Dominic, I will be the first time at your meetup, and wanted to ask how long the lightning talks are? And the speaker brings his own laptop? thanks, Alex.

**Comment by dominicletz** [comment]
@agreif 15 minutes, and yes

**Comment by agreif** [comment]
@dominicletz  I could talk about these 2 small topics:
- small text-to-speech module (hexdocs.pm/say)
- RiotJS with Phoenix

it would be approx 15 mins. would it be ok?
thanks, Alex.

**Comment by Efesto** [comment]
I have a lighting talk about remote journaling as alternative to remote daily.

Should be around 8 mins.

Am I still on time?
