### ISSUE TITLE
Talk proposal bits and pieces 

### ISSUE THREAD

**Issue by sebastiw** [elixir-berlin/planning#80]
### Your name

Sebastian Olsson

### Your GitHub

Github.com/sebastiw

### Your proposal type: talk, lightning talk or til (today I learned)

Talk

### Title of your presentation

Bits and pieces

### Description

About codecs and how fun it is to understand the meaning of underlying protocols and why the beam is perfect for it.

### Favourite Month you would like to present in

August

**Comment by dominicletz** [comment]
Hey @sebastiw thanks for submitting your proposal. We would like to invite you as the second speaker in August. For organizational reasons we will have to move the meetup to the 24th of August though. Let me know if that doesn't work for you ❤️

**Comment by dominicletz** [comment]
Thanks for doing this! And let us know when you would like to present something again!
