### ISSUE TITLE
Solving Kaggle competition with Explorer and a bit of ML

### ISSUE THREAD

**Issue by nickgnd** [elixir-berlin/planning#81]
### Your name

Nicolò Gnudi

### Your GitHub

https://github.com/nickgnd/

### Your Twitter (or other social link)

nickgnd

### Your proposal type: talk, lightning talk or til (today I learned)

talk

### Title of your presentation

Predicting Titanic survivors with Explorer and ML 🧊🛳️ 

### Description

Learning a bit of data science tricks can be a useful skill to accomplish our daily tasks: fraud detection, customer habits, etc.

In this talk we will solve together a classic Kaggle competition: ["Titanic - Machine Learning from Disaster"](https://www.kaggle.com/competitions/titanic/overview) using Explorer and traditional Machine Learning techniques.

We will start by loading the data, exploring it and trying to make sense of the dataset to eventually predict who will survive based on Titanic passengers data (name, age, price of ticket, etc.).

Cheers ✌️

### Favourite Month you would like to present in

November

**Comment by dominicletz** [comment]
Hey @nickgnd thtanks for pinging on discord, for some reason I didn't have the watch here. Your favorite month is November, so I added you now to the upcoming meetup on November 9th (the day after tomorrow).

Cheers!

**Comment by MMore** [comment]
Hey @nickgnd ,

We would like to accept you for this Nov Meetup. Sounds like a great talk :-) Can you confirm that this Thursday works for you, please? Thank you!

**Comment by nickgnd** [comment]
@MMore 

> Can you confirm that this Thursday works for you, please?

Yes 🤩 
Thank you!
