### ISSUE TITLE
Concurrency: Erlang and Elixir's secret sauce to scale and resilience

### ISSUE THREAD

**Issue by francescoc** [elixir-berlin/planning#83]
### Your name

Francesco Cesarini

### Your GitHub

https://github.com/francescoc

### Your Twitter (or other social link)

https://twitter.com/francescoc

### Your proposal type: talk, lightning talk or til (today I learned)

45 minute talk

### Title of your presentation

Concurrency: Erlang and Elixir's secret sauce to scale and resilience

### Description

Abstract: The concurrent paradigm has been influencing mainstream languages for decades, making developers more efficient, resilient and scalable code whilst helping reduce maintenance costs. As we are faced with a programming model that needs to scale on multi-core architectures and distributed environments, concurrency becomes even more critical. In these concurrency models, immutability, a key feature of functional programming paradigm will become even more evident. In this talk, we explain why!

Bio: Francesco Cesarini is the founder of [Erlang Solutions](https://www.erlang-solutions.com/). He has worked with the Erlang Ecosystem on a daily basis since 1995, starting as an intern at Ericsson’s computer science laboratory. He moved on to Ericsson’s Erlang training and consulting arm working on the first release of OTP, applying it to turnkey solutions and flagship telecom applications. In 1999, soon after Erlang was released as open source, he founded Erlang Solutions, which has become the world leader in Erlang and Elixir based consulting, contracting, training and systems development.

Francesco has worked in major Erlang-based projects both within and outside Ericsson, and as Technical Director, has led the development and consulting teams at Erlang Solutions. He is also the co-author of ‘Erlang Programming’ and ‘Designing for Scalability with Erlang/OTP’ both published by O’Reilly and lectures at Oxford University.

### Favourite Month you would like to present in

February

**Comment by dominicletz** [comment]
You're in @francescoc I've added you to the agenda: https://www.meetup.com/de-DE/elixir-berlin/events/298047032/

**Comment by slashmili** [comment]
Thanks @francescoc 🙏🏼 Enjoyed your talk 💜
