### ISSUE TITLE
Data Labelling is Good for You

### ISSUE THREAD

**Issue by maciejgryka** [elixir-berlin/planning#84]
### Your name

Maciej Gryka 

### Your GitHub

https://github.com/maciejgryka

### Your Twitter (or other social link)

@maciejgryka 

### Your proposal type: talk, lightning talk or til (today I learned)

Talk

### Title of your presentation

Data Labelling is Good for You

### Description

(this is a talk I will give at ElixirConf EU in April https://www.elixirconf.eu/talks/data-labelling-is-good-for-you/)

In the age of AI, data is crucial. In this talk, I will try to convince you that creating your own data labeling pipeline is a critical part of using AI in your business and that Elixir is a great tool for it. While it’s unlikely you will produce a dataset of the size used by tech giants, I will argue that small data specific to your use-case is extremely valuable and that the process of labeling is valuable in itself.
I will walk through how we did this internally, what challenges we faced, how we solved them and what we learned in the process.

### Favourite Month you would like to present in

March

**Comment by dominicletz** [comment]
I've got you marked for March! :purple_heart:

**Comment by maciejgryka** [comment]
Great, thanks @dominicletz!

**Comment by dominicletz** [comment]
Thanks for your talk!
