### ISSUE TITLE
Format Elixir code in Markdown code blocks

### ISSUE THREAD

**Issue by angelikatyborska** [elixir-berlin/planning#85]
### Your name

Angelika Tyborska

### Your GitHub

https://github.com/angelikatyborska/

### Your Twitter (or other social link)

https://mas.to/@angelikatyborska

### Your proposal type: talk, lightning talk or til (today I learned)

lightning talk

### Title of your presentation

Format Elixir code in Markdown code blocks

### Description

I recently created this tiny formatter plugin that allows you to format Elixir code that's in code blocks in Markdown files (https://hexdocs.pm/markdown_code_block_formatter/readme.html). I would like to very briefly mention why I did that and how, and generally just spread awareness of this library.

### Favourite Month you would like to present in

February

**Comment by dominicletz** [comment]
Confirmed for February as lightning talk :purple_heart:

**Comment by slashmili** [comment]
Thanks a lot @angelikatyborska  

I did enjoy and learn new things about the formatter 🙏🏼
