### ISSUE TITLE
Building a Large-Scale, Streaming-Based Logging and Monitoring Solution with Clojure

### ISSUE THREAD

**Issue by cresh** [elixir-berlin/planning#87]
### Your name

Marcus Crestani

### Your GitHub

https://github.com/cresh

### Your proposal type: talk, lightning talk or til (today I learned)

lightning talk

### Title of your presentation

Building a Large-Scale, Streaming-Based Logging and Monitoring Solution with Clojure

### Description

I am here for BOBKONF and would be happy to share what I am working on in a 5-minute lightning talk during the March 14th Elixir/Clojure event. This is my abstract:

> In a semiconductor fab, numerous processes play a role in manufacturing a microchip. Keeping track of the manufacturing process, recording all the data and metrics that occur in the different steps, sending alerts when parameters indicate production problems, and correlating the data with the resulting product is essential for a successful and efficient production.
> 
> We show how we have built a large-scale logging and monitoring solution of a large and heterogenous legacy enterprise IT infrastructure that controls semiconductor manufacturing. Our streaming-based system uses as specialized DSL on top of Clojure and handles more than 5,000 events per second, stores terabytes of logs and metrics persistently in Elasticsearch and Prometheus, and provides visualizations with Kibana and Grafana and real-time alerting with Alertmanager.

### Favourite Month you would like to present in

March

**Comment by dominicletz** [comment]
You're in! Looking forward to see and hear you in Berlin

**Comment by dominicletz** [comment]
Thanks for your talk!
