### ISSUE TITLE
Lightning Talk Proposal: `defrecord` is not enough

### ISSUE THREAD

**Issue by kaaninho** [elixir-berlin/planning#88]
### Your name

Kaan

### Your GitHub

https://github.com/kaaninho

### Your proposal type: talk, lightning talk or til (today I learned)

lightning talk

### Title of your presentation

`defrecord` is not enough

### Description

Records are a useful thing! With records, we can name a collection of fields and ascribe _meaning_ to it, because sometimes it's not "just a map". But sadly, Clojure's built-in records are insufficient. They don't always behave the way we know from other programming languages.

In this talk we will discuss deficiencies of `defrecord` and show a way out: Use the power of Lisp to build your own data types!

### Favourite Month you would like to present in

March

**Comment by dominicletz** [comment]
Hey @kaaninho thanks for submitting. You're in! So be ready to present this during lightning talk section.

**Comment by dominicletz** [comment]
Thanks for your talk!
