### ISSUE TITLE
Local Advent of GPT

### ISSUE THREAD

**Issue by xhr15** [elixir-berlin/planning#89]
### Your name

Chris

### Your GitHub

https://github.com/xhr15

### Your Twitter (or other social link)

https://twitter.com/chris_bitcrowd

### Your proposal type: talk, lightning talk or til (today I learned)

talk

### Title of your presentation

Local Advent of GPT (follow up)

### Description

In the January edition, https://github.com/dominicletz introduced us to code generation with ChatGPT and asked, if, and how, this can be improved. 

In this talk, we will touch briefly on how to run local models that are capable of code generation, what prompts might be helpful, and how agents might help there.

We will use https://github.com/dominicletz [January talk ](https://github.com/dominicletz/advent_of_chatgpt) as starting point and see, how far a local approach might bring us.

### Favourite Month you would like to present in

March

**Comment by MMore** [comment]
Amazing topic, really looking forward to it @xhr15 !!! 
We keep the 2nd slot in our special Bobkonf Clojure+Elixir event open for a Clojure talk. Do you think, April would work for you, too?

**Comment by dominicletz** [comment]
Yeah, for March we only have lightning talk slots left in March, but I would really hear this one in full length. So April?

**Comment by xhr15** [comment]
Yes, as discussed on Slack, April would be great

**Comment by slashmili** [comment]
Thanks @xhr15! It was a great talk!
