### ISSUE TITLE
Talks / proposals / requests for May

### ISSUE THREAD

**Issue by duksis** [elixir-berlin/planning#9]
Please put talk proposals / requests in this issue 
when proposing a talk please provide the approximate length you would need for it.

we should have 3 slots of 30 min each open for May

**Comment by duksis** [comment]
I can do a "war story" on 
* a real life service evolving through "synchronous pipeline" => "streams" => "GenStage"
or 
* transforming large amounts of json with elixir

**Comment by duksis** [comment]
@slashmili @devonestes @zampino @jaigouk would any of you be up for doing a short talk and experience summary from Elixir conf EU at the thursdays meetup?

**Comment by jaigouk** [comment]
@duksis 
I tried to tweet most of links i can catch while watching talks. https://twitter.com/jaigouk

I am open to talk 5~10 min short one. I also found this link 
https://github.com/Tuxified/elixirconf-eu-2017

**Comment by jaigouk** [comment]
@duksis I talked with my colleague @nTraum. I think we can provide place to gather in the future.

**Comment by zampino** [comment]
Sounds good, we can have a distributed informal quatsch and share such
links or so...

**Comment by devonestes** [comment]
@duksis I actually can't make it on Thursday. I forgot my wife's out of town and I'm single parenting for a week...

**Comment by duksis** [comment]
@jaigouk your impressions in 5~10 min would be great as well and and we can have a open discussion with a beer

**Comment by jaigouk** [comment]
@duksis got it. i will prepare the talk. I hope it's worth to share the experience.

**Comment by jaigouk** [comment]
updated some links https://github.com/jaigouk/elixirconf-eu-2017
