### ISSUE TITLE
Live coding: Interview challenge

### ISSUE THREAD

**Issue by Overbryd** [elixir-berlin/planning#90]
### Your name

Lukas Rieder

### Your GitHub

https://github.com/Overbryd

### Your proposal type: talk, lightning talk or til (today I learned)

talk

### Title of your presentation

Interview coding

### Description

I recently came across a cool coding interview challenge and I wanted to share the experience with you, live, coding.

Hop along an entertaining talk, some problem solving and live coding performance.

### Favourite Month you would like to present in

August

**Comment by slashmili** [comment]
Looking forward to your talk @Overbryd!

**Comment by dominicletz** [comment]
Enjoyed this very much. Thanks @Overbryd !
